### ISSUE TITLE
Grafana 9.x upgrade

### ISSUE THREAD

**Issue by devrimdemiroz** [aws/amazon-managed-grafana-roadmap#30]
Hi,

Is there any visible forecast for AMG Grafana 9.x upgrade?

Kind regards,
Devrim

**Comment by fentonfentonfenton** [comment]
➕ 1️⃣  on this

**Comment by fentonfentonfenton** [comment]
@mhausenblas it's hard to find much/anything about what versions are and/or will be supported - can you point me to anywhere?

**Comment by mhausenblas** [comment]
We’re considering this in H1/2023.  I'm curious if there are features in 9.x that you’re interested in specifically?

**Comment by brettdh** [comment]
Our team is especially interested in Unified Alerting, which is the default in 9.x and no longer requires opt in as in #9 (and opt-in doesn't appear to be possible in earlier versions, since it requires modifying a config file we don't have access to in AMG).

**Comment by bml1g12** [comment]
> We’re considering this in H1/2023. I'm curious if there are features in 9.x that you’re interested in specifically?

These v9 plugin's seem very useful, I'd be grateful if anyone is aware of a sensible alternative to these features on v8 AWS Managed Graphana, as it looks like we may need to switch to self-managed Graphana to take advantage of these features:

- https://grafana.com/grafana/plugins/computest-cloudwatchalarm-datasource/ such that we can create a summary table of alarm state across many many cloudwatch alarms (to create the alarm using Grafana alarms instead seems to require making a graph for every cloudwatch metric)
- https://grafana.com/products/oncall/ for easy escalation / incident management
- https://grafana.com/docs/grafana/latest/alerting/contact-points/message-templating/create-message-template/ such that a single alert can send different notification messages depending on the alert context (which seems related to https://g-b86f4c3763.grafana-workspace.ap-northeast-1.amazonaws.com/plugins/alertmanager) ... Maybe this is already supported according in v8 according to [AWS docs](https://docs.aws.amazon.com/grafana/latest/userguide/alerts-notification-templating.html), but Grafana docs linked in those AWS docs seem to refer heavily to Contact Points in v9, so a bit confused. 
Is it possible to create a "message template" like that described [here](https://grafana.com/docs/grafana-cloud/alerting/contact-points/message-templating/)?

- Ability to test Alert notifications - this seems to be a 8.2 feature but missing currently? https://grafana.com/blog/2021/10/12/new-in-grafana-8.2-test-contact-points-for-alerts-before-they-fire/

**Comment by fentonfentonfenton** [comment]
> Our team is especially interested in Unified Alerting, which is the default in 9.x and no longer requires opt in as in #9 (and opt-in doesn't appear to be possible in earlier versions, since it requires modifying a config file we don't have access to in AMG).

Would be great if before 9.x it was possible to switch on feature flags

**Comment by danshoop** [comment]
Our team is currently investigating AMG, yet the significant fall behind in releases is a critical concern. The current AMG is stuck at last February's 8.4 release with several significant 8.5 updates since still unimplemented in AMG. v9.0 was released a quarter ago now and has had significant feature enhancements and numerous changes, and v9.4 is most likely to be announced before GrafanaCon on Nov 1st. 

With the AMG team's roadmap only _**"considering"**_ v9.x in 2023H1 that suggests we won't likely see it released until next June. With Grafana's roadmap of a major release each year, that would mean by the time we get v9, Grafana will be at v10 and fallen hopelessly behind. 

There's a lot to like in v9, significant changes, alerting improvements, incident management integration and more. My SRE team and I will be attending GrafanaCon and if we choose AMG we'll be learning about a product that isn't even being considered yet by AWS and likely not to arrive until a year after it's release. That's not a good value proposition for choosing AMG, and asking us _why_ we'd have an interest in seeing the latest major release doesn't indicate there's good attenuation by the AMG Team to Grafana users. We want it because it's a major update with major new features  -- the new chart types, incident management and alerting improvements alone are reasons to upgrade to v9.x; unfortunately if we choose AMG seems like we're not likely to get the benefit of 2022 technology until it's already a year stale. 

So why should you more strongly consider getting v9.3 (or even v8.5) out the door this quarter? Because Grafana customers will want the new significant features and updates and will have needed to move on to these versions, and likely will mean leaving AMG for other implementations. 

Please "consider" updates to be necessary, essential, and most importantly, much more frequent .

**Comment by aam1r** [comment]
> We’re considering this in H1/2023. I'm curious if there are features in 9.x that you’re interested in specifically?

We are considering migrating from a self-hosted Grafana v9 deployment and would need the features from v9 to be able to migrate. Downgrading back to Grafana v8 is not an option due to loss of functionality and extra work that would be needed to rework dashboards and panels.

Since we are in H1 2023 now, would you happen to have a more accurate time estimate?

Thank you, Michael.

**Comment by mengdic** [comment]
> > We’re considering this in H1/2023. I'm curious if there are features in 9.x that you’re interested in specifically?
> 
> We are considering migrating from a self-hosted Grafana v9 deployment and would need the features from v9 to be able to migrate. Downgrading back to Grafana v8 is not an option due to loss of functionality and extra work that would be needed to rework dashboards and panels.
> 
> Since we are in H1 2023 now, would you happen to have a more accurate time estimate?
> 
> Thank you, Michael.

Hi Aamir, would you mind email [aws-grafana-feedback@amazon.com](mailto:aws-grafana-feedback@amazon.com)? I will be happy to assist you with more details.

**Comment by rsheldon-sincro** [comment]
Providing a managed service like this which lags so far behind current versions available elsewhere is very frustrating.  There are many improvements and additional in the newer versions that improve the user experience. What is Amazon's policy for upgrading Grafana? I expect some lag as you integrate and validate newer versions

8.4 was released in Feb 2022
8.4.7 was released in April 2022 (this appears to be Amazon's current version)
9.0 was released in June 2022
9.4 was released in Feb 2023

So we're almost a year out-of-date.

**Comment by Samobo** [comment]
Is there any news about this? Like a more accurate estimate of the release date?

**Comment by aldanor** [comment]
@mengdic Any updates on the timeline for 9.x please?

Latest Grafana is v9.4.7, and 9.5 will be out shortly, when will the AMG be updated?

**Comment by ievgen-golubiev** [comment]
> @mengdic Any updates on the timeline for 9.x please?
version 9.4 already available to setup on AWS

**Comment by brettdh** [comment]
> version 9.4 already available to setup on AWS

Huh, so it is: 
![image](https://user-images.githubusercontent.com/91550/235159064-2dd0eae3-2fb0-4aa5-b87c-30edc0d9aa0d.png)

I wonder how long that's been there. I wasn't able to find any [AWS News Blog](https://aws.amazon.com/blogs/aws/) post about this update.

I'd still appreciate any update on the significant lag detailed above, and whether there are plans to reduce it going forward.

**Comment by ievgen-golubiev** [comment]
@brettdh I was surprised too. Just found it today. And it is not even mentioned in [Document history](https://docs.aws.amazon.com/grafana/latest/userguide/doc-history.html)

**Comment by mengdic** [comment]
Hi all, it was deployed to all supported regions (besides Asia Pacific - Seoul) today. 👀 glad to see the communities fast react to it. 

I will have the user doc, what's new post, official announcement as well as a nice user blog to share today.

**Comment by mengdic** [comment]
Hi All, Amazon Managed Grafana now supports workspace configuration with version 9.4 option 

With this release, you can select an Amazon Managed Grafana supported version to create a new workspace. Version 9.4 includes several new features to further enhance your experience in Amazon Managed Grafana including, but not limited to: plugin enhancements to support CloudWatch cross-account querying, OpenSearch serverless, querying multiple asset properties from AWS IoT Sitewise, query result reuse and async queries for Athena; Prometheus and Loki query builders make it even easier to create and modify queries for your data sources; Service accounts that provide a secure and efficient way to automate tasks within your Grafana instance.

To explore the complete list of new features, please refer to the [user documentation here](https://docs.aws.amazon.com/grafana/latest/userguide/using-grafana-v9.html). Follow the instructions [here](https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-workspace.html) to configuring workspaces with version 9.4. To migrate an existing workspace, check out [amazon-managed-grafana-](https://github.com/aws-observability/amazon-managed-grafana-migrator)

Want to learn more? 
•	[What’s New](https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-managed-grafana-workspace-configuration-version-9-4-option/)
•	[Blog](https://aws.amazon.com/blogs/mt/announcing-amazon-managed-grafana-workspace-version-selection-with-version-9-4-support/)
•	[User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/using-grafana-v9.html)

**Comment by virajith-lk** [comment]
If someone needs to migrate from AMG 8.4 to 9.4 (copy contents from previous AMG 8.4 workspace to a new 9.4 one), following tool can be used!
https://github.com/aws-observability/amazon-managed-grafana-migrator

**Comment by rsheldon-sincro** [comment]
Looks like the in-place upgrade is now available, according to https://github.com/aws/amazon-managed-grafana-roadmap/issues/56
