### ISSUE TITLE
Unified alerting

### ISSUE THREAD

**Issue by IzekChen** [aws/amazon-managed-grafana-roadmap#9]
Since Grafana is moving away from the legacy dashboard alerting and have lots of enhancement on the alerting feature.

I personally would like to see that feature on AMG and that would provide better observability experience to DevOps/SRE for monitoring. And also more flexibility with the unified alerting

**Comment by mhausenblas** [comment]
Thanks @IzekChen and to clarify: is this specifically around unified alerting features only or also (in addition) aspects like scalability or HA that you're looking for?

**Comment by amandeep-r** [comment]
I'd like the ability to use the unified alerting system because I want to alert on numeric, tabular data rather than on time series. Here is a [link](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/fundamentals/evaluate-grafana-alerts/) to the relevant section of the Grafana documentation describing this.

Do you know where this feature is on the roadmap and what its priority is?

**Comment by mjhanke** [comment]
My team's usage of AMG is blocked on support for unified alerting. Is there any information about this feature's position on the roadmap?

**Comment by mengdic** [comment]
Hello All, Grafana Alerting is now available in Amazon Managed Grafana. 
Read more here in the [Amazon Managed Grafana user guide](https://docs.aws.amazon.com/grafana/latest/userguide/alerts-overview.html).

**Comment by emretoptanci** [comment]
Does this also include some improvements about notification channels?
For example, MS Teams support or at least more alarm details in the event sent to AWS SNS?
